#!/usr/bin/env bash
# This script runs all scripts in the runs directory that match the provided grep pattern.
# It is intended to be used for running environment setup scripts.
# This script is a modified version of ThePrimeagen's run script - https://github.com/ThePrimeagen/dev/blob/master/run
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

grep=""
dry_run="0"

# Check input args
while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    else
        grep="$1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "RUN: env: $env -- grep: $grep"

# Find all executable scripts in the runs directory
runs_dir=`find $script_dir/runs -mindepth 1 -maxdepth 1 -executable`

# Run all scripts in the runs directory
for s in $runs_dir; do
    # If run script does not match grep, skip it
    if basename $s | grep -vq "$grep"; then
        log "grep \"$grep\" filtered out $s"
        continue
    fi

    log "running script: $s"

    if [[ $dry_run == "0" ]]; then
        $s
    fi
done