#!/usr/bin/env bash

mkdir -p ~/.local/share/fonts

# Install fonts
wget https://use.fontawesome.com/releases/v6.5.0/fontawesome-free-6.5.0-desktop.zip -P ~/Downloads/
unzip ~/Downloads/fontawesome-free-6.5.0-desktop.zip -d ~/Downloads/
pushd ~/Downloads/fontawesome-free-6.5.0-desktop/
cp otfs/*.otf ~/.local/share/fonts/
cp ttf/*.ttf ~/.local/share/fonts/
popd


sudo apt install fonts-roboto -y
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"

# Reload font cache
fc-cache -fv