#!/usr/bin/env bash

# Install required packages
sudo apt install i3-wm i3 -y
sudo apt install rofi -y
sudo apt install polybar -y
sudo apt install nitrogen jq -y

# i3-lock-color
git clone https://github.com/Raymo111/i3lock-color.git
pushd i3lock-color
./install-i3lock-color.sh
popd
rm -rf i3lock-color

# Create configuration directories
mkdir -p ~/.config/i3
mkdir -p ~/.config/rofi
mkdir -p ~/.config/polybar
mkdir -p ~/.config/nitrogen

# Copy configuration files
cp -r ./env/.config/i3/ $HOME/.config/
cp -r ./env/.config/rofi/ $HOME/.config/
cp -r ./env/.config/polybar/ $HOME/.config/
cp -r ./env/.config/nitrogen/ $HOME/.config/