#!/usr/bin/env bash

sudo apt -y update
sudo apt -y install git ripgrep xclip jq tldr shutter python3-pip
sudp apt -y install pavucontrol

git clone git@github.com:junegunn/fzf.git $HOME/personal/fzf
$HOME/personal/fzf/install
