#!/usr/bin/env bash

sudo apt -y install zsh
hash -r
sudo chsh -s $(which zsh)
# Install Oh My Posh
curl -s https://ohmyposh.dev/install.sh | bash -s

# Copy zsh configuration
cp "$(pwd)/env/.zshrc" $HOME/.zshrc

# Copy Oh My Posh configuration
mkdir -p $HOME/.config/ohmyposh
cp "$(pwd)/env/.config/ohmyposh/config.toml" $HOME/.config/ohmyposh/config.toml

# Restart zsh
source $HOME/.zshrc