#!/usr/bin/env bash

sudo apt -y install zsh
hash -r
sudo chsh -s $(which zsh)
# Install Oh My Posh if not already installed
if ! command -v oh-my-posh &> /dev/null; then
  echo "Oh My Posh not found, installing..."
  curl -s https://ohmyposh.dev/install.sh | bash -s
else
  echo "Oh My Posh is already installed."
fi

# Copy zsh configuration
cp "$(pwd)/env/.zshrc" $HOME/.zshrc

# Copy Oh My Posh configuration
mkdir -p $HOME/.config/ohmyposh
cp "$(pwd)/env/.config/ohmyposh/config.toml" $HOME/.config/ohmyposh/config.toml

# Restart zsh
source $HOME/.zshrc